title: Rahul Guruprakash
logo: /assets/img/logo.png
description: Graduate Research Assistant @ NCSU
show_downloads: false
show_socialmedia: true
google_analytics:
theme: jekyll-theme-minimal
social_media:
  stackexchange: "https://stackoverflow.com/users/22665914/rahul-guruprakash"
  github: "https://github.com/g-rahul"
  linkedin: "https://linkedin.com/in/rahul-g-055720175"
